    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init
